<?php

use Illuminate\Database\Seeder;

class CMSTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {       
      DB::table('cms')->insert(
      [
		'id' => 1,
          'privacy_policy' => '<h3 class="t-darkblue fnt-bld mt-10">Changes to this privacy policy</h3><p class="content t-black">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages</p><h3 class="t-darkblue fnt-bld">Website Security</h3><p class="content t-black">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages</p><p class="content t-black">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages</p><h3 class="t-darkblue fnt-bld">Communications</h3><p class="content t-black">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages</p>',
          'tc' => ' <p class="content t-black">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages</p><p class="content  t-black">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages</p><p class="content  t-black">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages</p><p class="content  t-black">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages</p>',
          'aboutus' => " Yes. And and we’ve developed a state of the art audit process in order to prove to third parties, including our customers, that customer funds are properly held. See here for more information on our audit process.",
          'termsservice' => "<p>Lorem ipsum dolor sit amet, doming salutatus vix id, posse patrioque reformidans an pri. Eu vero tempor mel, dolore dictas no his. Ex pri solet blandit. Per congue laoreet cu, an usu essent causae repudiare. Pro eu nulla ludus labores, nec dictas pericula suavitate eu, mnesarchum sadipscing ei mel. Mei ad feugiat conclusionemque, saepe expetenda cu eos. </p> <p>Graecis explicari accommodare his te, hinc wisi qui cu. Latine delicata nec ad, ea suas movet legimus est, ad elit dictas dicunt cum. Nec partem molestie disputationi ex, no zril accusam vim. Tollit cetero cum no. Amet etiam viderer id mea. Mundi zril soluta per an, putent platonem intellegam vix at, eu cum vero doming. Reque congue reprehendunt sit cu, mel solet accusata interpretaris in.</p><p>Utinam officiis evertitur cum cu, reque dignissim percipitur vel ex, ei tale libris postea pri. Eam at constituam mediocritatem, est ne eius imperdiet deseruisse. Appetere atomorum per te. Vix brute nullam debitis no.</p><p>Doming malorum te pro, at vide periculis quo. Cibo melius eos ea, dicta pertinacia in sea. Id vim nostro nominati voluptatibus, vim consul meliore sensibus cu. Quod diam forensibus an vim, eu tincidunt definitionem his. Persius assueverit eum at, quando consectetuer voluptatibus cu pri, erant soleat dissentiunt eam no. </p><p>Mea et discere fabellas recusabo. Et sint iusto efficiendi est, laudem option percipitur ea vix, nam ludus elaboraret in. Eripuit euismod neglegentur pri at, dico labitur corrumpit duo an. Ad reque atqui sea, usu ut primis prompta. Ne ius bonorum tacimates intellegat, id eam ceteros omnesque noluisse.</p> <p>Tantas omnesque sapientem ut vis. Esse suavitate ex vim. Quo an commodo officiis. Ignota essent ius no, vero erroribus te qui. Eum no velit nihil referrentur. In per unum lorem. </p> <p>Cum harum inimicus ne, sea an odio euismod laoreet. Ex cum idque scriptorem, ius ex liber labores qualisque. Mel causae iisque id, epicuri disputationi et has. Ei primis feugiat civibus quo, sit eu decore perfecto, vel et cetero vivendo. Dicant efficiendi vel ei, duo ne inermis deserunt tractatos, ei prompta admodum nostrum quo. </p>  <p>Sit ne doctus ocurreret laboramus, an idque explicari hendrerit mei. Utinam fastidii definitionem ad eam. Officiis accusata ex vel, nobis oratio vel et. Cum consectetuer interpretaris ad. An pro vidisse tibique, ex dissentiunt theophrastus mei. </p> <p>Ea decore convenire deseruisse vim, option meliore nec te. Quo ad possit contentiones. Et nam wisi voluptaria, facer tamquam ea eum. An est ferri ancillae. Cetero fuisset nec no. </p> <p>Ex ius fabulas placerat. Quo ridens sadipscing reprehendunt ex, at pro impetus signiferumque. Feugiat consequuntur et sea, has ei debet signiferumque, noster omnium tibique mei te. Est ad modo debet regione. Pri quidam tibique te. Altera docendi mei ei, id mei summo vidisse reprehendunt.</p>",
          'homebanner' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley",
          'logo' => "logo.png",
          'favicon' => "favicon.png",
          'created_at' => date("Y-m-d H:i:s"),
           'updated_at' => date("Y-m-d H:i:s"),     
      ]);
    }
}